#!/usr/bin/env php
<?php

/**
 * Entry point for hd-wallet-derive.
 *
 * Code in this file is related to interacting with the shell.
 */

// Let's be strict about things.
require_once __DIR__ . '/vendor/autoload.php';
\strictmode\initializer::init();


use App\Utils\MyLogger;
use App\WalletDerive;
use App\mnemonic;
use App\Utils\WalletDeriveReport;
use App\Utils\Util;



/**
 * Our main function.  It performs top-level exception handling.
 */
function main()
{
    // why limit ourselves?    ;-)
    ini_set('memory_limit', -1 );

    try
    {
        // CLI Parameters processing
        $orig_params = Util::getCliParams();
        list( $params, $success ) = Util::processCliParams();
        if( $success != 0 )
        {
            return $success;
        }

        // Creates WalletDerive object
        $walletDerive = new WalletDerive($params);
        if($params['gen-key']) {
            $result = $walletDerive->genRandomKeys();
            WalletDeriveReport::printResults($params, [$result]);
            return 0;
        }

        if($params['mnemonic']) {
            $mnemonic = explode(' ', $params['mnemonic']);  // spaces already normalized.
            $seed = mnemonic::decode($mnemonic);
            $seedinfo = ['seed' => $seed, 'mnemonic' => $params['mnemonic']];
            $keys = $walletDerive->genKeysFromSeed($seedinfo);
            
            if($params['wallet-keys']) {
                WalletDeriveReport::printResults($params, [$keys]);
                return 0;
            }
            
            $params['view-priv'] = $keys['view-key-private'];
            $params['spend-pub'] = $keys['spend-key-public'];
            $walletDerive = new WalletDerive($params);
        }
        else if($params['seed']) {
            $seed = trim($params['seed']);
            $seedinfo = ['seed' => $seed, 'mnemonic' => implode(' ', mnemonic::encode_with_checksum($seed))];
            $keys = $walletDerive->genKeysFromSeed($seedinfo);
            
            if($params['wallet-keys']) {
                WalletDeriveReport::printResults($params, [$keys]);
                return 0;
            }
            
            $params['view-priv'] = $keys['view-key-private'];
            $params['spend-pub'] = $keys['spend-key-public'];
            $walletDerive = new WalletDerive($params);            
        }
        
        // $key = @$params['key'] ?: $walletDerive->mnemonicToKey($params['coin'], $params['mnemonic'], $params['key-type'], $params['mnemonic-pw']);
        $addrs = $walletDerive->derive_keys();

        // Prints result
        echo "\n";
        WalletDeriveReport::printResults($params, $addrs);
        return 0;
    }
    catch(Exception $e)
    {
        MyLogger::getInstance()->log_exception( $e );
        // print validation errors to stderr.
        if( $e->getCode() == 2 ) {
            fprintf( STDERR, $e->getMessage() . "\n\n" );
        }
        return $e->getCode() ?: 1;
    }
}

exit(main());
