#!/usr/bin/env php
<?php

/**
 * Entry point for subaddress-derive-xmr CLI utility.
 *
 * copyright (c) Dan Libby 2019
 * 
 * Use of this software is subject to the terms of the
 * GNU GENERAL PUBLIC LICENSE Version 3.
 * See included LICENSE file or if missing
 * https://www.gnu.org/licenses/gpl-3.0.en.html.
 *
 * Code in this file is related to interacting with the shell.
 */

// Let's be strict about things.
require_once __DIR__ . '/vendor/autoload.php';
\strictmode\initializer::init();


use App\Utils\MyLogger;
use App\WalletDerive;
use danda\monero\mnemonic\mnemonic;
use App\Utils\WalletDeriveReport;
use App\Utils\Util;



/**
 * Our main function.  It performs top-level exception handling.
 */
function main()
{
    // why limit ourselves?    ;-)
    ini_set('memory_limit', -1 );

    try
    {
        // CLI Parameters processing
        $orig_params = Util::getCliParams();
        list( $params, $success ) = Util::processCliParams();
        if( $success != 0 )
        {
            return $success;
        }

        // Creates WalletDerive object
        $walletDerive = new WalletDerive($params);
        if($params['gen-wallet']) {
            $result = $walletDerive->genRandomKeys();
            WalletDeriveReport::printResults($params, [$result]);
            return 0;
        }

        if($params['mnemonic']) {
            $mnemonic = explode(' ', $params['mnemonic']);  // spaces already normalized.
            $mnemonic_ws = mnemonic::find_wordset_by_mnemonic($mnemonic);
            if(!$mnemonic_ws) {
                throw new \Exception("Unrecognized word in mnemonic phrase");
            }            
            $ws = mnemonic::get_wordset_by_name($mnemonic_ws);
            if( !mnemonic::validate_checksum($mnemonic, $ws['prefix_len'] )) {
                throw new Exception("Invalid checksum.  One or more words is incorrect or missing.");
            }
            $seed = mnemonic::decode($mnemonic, $mnemonic_ws);
            $seedinfo = ['seed' => $seed,
                         'mnemonic' => $params['mnemonic'],
                         'wordset' => $params['wordset']
            ];
            $keys = $walletDerive->genKeysFromSeed($seedinfo);
            
            if($params['wallet-keys']) {
                WalletDeriveReport::printResults($params, [$keys]);
                return 0;
            }
            
            $params['view-priv'] = $keys['view-key-private'];
            $params['spend-pub'] = $keys['spend-key-public'];
            $walletDerive = new WalletDerive($params);
        }
        else if($params['seed']) {
            $seed = trim($params['seed']);
            $seedinfo = ['seed' => $seed,
                         'mnemonic' => implode(' ', mnemonic::encode_with_checksum($seed, $params['wordset'])),
                         'wordset' => $params['wordset']
            ];
            $keys = $walletDerive->genKeysFromSeed($seedinfo);
            
            if($params['wallet-keys']) {
                WalletDeriveReport::printResults($params, [$keys]);
                return 0;
            }
            
            $params['view-priv'] = $keys['view-key-private'];
            $params['spend-pub'] = $keys['spend-key-public'];
            $walletDerive = new WalletDerive($params);            
        }
        
        // $key = @$params['key'] ?: $walletDerive->mnemonicToKey($params['coin'], $params['mnemonic'], $params['key-type'], $params['mnemonic-pw']);
        $addrs = $walletDerive->derive_keys();

        // Prints result
        echo "\n";
        WalletDeriveReport::printResults($params, $addrs);
        return 0;
    }
    catch(Exception $e)
    {
        MyLogger::getInstance()->log_exception( $e );
        // print validation errors to stderr.
        if( $e->getCode() == 2 ) {
            fprintf( STDERR, $e->getMessage() . "\n\n" );
        }
        return $e->getCode() ?: 1;
    }
}

exit(main());
